version: "3"
services:
  php:
    build: ./docker/web
    container_name: server_php_mongo
    restart: always
    depends_on:
      - db
    ports:
      - 8000:80
    volumes:
      - ./app/:/var/www/
      - ./docker/apache2/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/apache2/var/log/:/var/log/apache2
    networks:
      - app-network
  
  db:
    image: mongo
    container_name: mongo_db
    ports:
      - 27018:27017
    volumes:
      - ./docker/db:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
